// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x000E,
        "selector-operation:_Pack6:0x000E:stack-word-immediate:16",
        "DateString",
    ),
    SelectorOperationRoute::new(
        0x0010,
        "selector-operation:_Pack6:0x0010:stack-word-immediate:16",
        "TimeString",
    ),
    SelectorOperationRoute::new(
        0x0014,
        "selector-operation:_Pack6:0x0014:stack-word-immediate:16",
        "LongDateString",
    ),
    SelectorOperationRoute::new(
        0x0016,
        "selector-operation:_Pack6:0x0016:stack-word-immediate:16",
        "LongTimeString",
    ),
    SelectorOperationRoute::new(
        0x001A,
        "selector-operation:_Pack6:0x001A:stack-word-immediate:16",
        "CompareText",
    ),
    SelectorOperationRoute::new(
        0x001C,
        "selector-operation:_Pack6:0x001C:stack-word-immediate:16",
        "IdenticalText",
    ),
    SelectorOperationRoute::new(
        0x001E,
        "selector-operation:_Pack6:0x001E:stack-word-immediate:16",
        "ScriptOrder",
    ),
    SelectorOperationRoute::new(
        0x0020,
        "selector-operation:_Pack6:0x0020:stack-word-immediate:16",
        "LanguageOrder",
    ),
    SelectorOperationRoute::new(
        0x0022,
        "selector-operation:_Pack6:0x0022:stack-word-immediate:16",
        "TextOrder",
    ),
]
