// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0001,
        "selector-operation:_HighLevelFSDispatch:0x0001:d0-moveq-immediate:8",
        "FSMakeFSSpec",
    ),
    SelectorOperationRoute::new(
        0x0002,
        "selector-operation:_HighLevelFSDispatch:0x0002:d0-moveq-immediate:8",
        "FSpOpenDF",
    ),
    SelectorOperationRoute::new(
        0x0003,
        "selector-operation:_HighLevelFSDispatch:0x0003:d0-moveq-immediate:8",
        "FSpOpenRF",
    ),
    SelectorOperationRoute::new(
        0x0004,
        "selector-operation:_HighLevelFSDispatch:0x0004:d0-moveq-immediate:8",
        "FSpCreate",
    ),
    SelectorOperationRoute::new(
        0x0005,
        "selector-operation:_HighLevelFSDispatch:0x0005:d0-moveq-immediate:8",
        "FSpDirCreate",
    ),
    SelectorOperationRoute::new(
        0x0006,
        "selector-operation:_HighLevelFSDispatch:0x0006:d0-moveq-immediate:8",
        "FSpDelete",
    ),
    SelectorOperationRoute::new(
        0x0007,
        "selector-operation:_HighLevelFSDispatch:0x0007:d0-moveq-immediate:8",
        "FSpGetFInfo",
    ),
    SelectorOperationRoute::new(
        0x0008,
        "selector-operation:_HighLevelFSDispatch:0x0008:d0-moveq-immediate:8",
        "FSpSetFInfo",
    ),
    SelectorOperationRoute::new(
        0x0009,
        "selector-operation:_HighLevelFSDispatch:0x0009:d0-moveq-immediate:8",
        "FSpSetFLock",
    ),
    SelectorOperationRoute::new(
        0x000A,
        "selector-operation:_HighLevelFSDispatch:0x000A:d0-moveq-immediate:8",
        "FSpRstFLock",
    ),
    SelectorOperationRoute::new(
        0x000B,
        "selector-operation:_HighLevelFSDispatch:0x000B:d0-moveq-immediate:8",
        "FSpRename",
    ),
    SelectorOperationRoute::new(
        0x000C,
        "selector-operation:_HighLevelFSDispatch:0x000C:d0-moveq-immediate:8",
        "FSpCatMove",
    ),
    SelectorOperationRoute::new(
        0x000D,
        "selector-operation:_HighLevelFSDispatch:0x000D:d0-moveq-immediate:8",
        "FSpOpenResFile",
    ),
    SelectorOperationRoute::new(
        0x000E,
        "selector-operation:_HighLevelFSDispatch:0x000E:d0-moveq-immediate:8",
        "FSpCreateResFile",
    ),
    SelectorOperationRoute::new(
        0x000F,
        "selector-operation:_HighLevelFSDispatch:0x000F:d0-moveq-immediate:8",
        "FSpExchangeFiles",
    ),
]
