// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x800E001C,
        "selector-operation:_ScriptUtil:0x800E001C:stack-long-immediate:32",
        "HiliteText",
    ),
    SelectorOperationRoute::new(
        0x8012FFE2,
        "selector-operation:_ScriptUtil:0x8012FFE2:stack-long-immediate:32",
        "NFindWord",
    ),
    SelectorOperationRoute::new(
        0x8012FFFC,
        "selector-operation:_ScriptUtil:0x8012FFFC:stack-long-immediate:32",
        "GetFormatOrder",
    ),
    SelectorOperationRoute::new(
        0x82040022,
        "selector-operation:_ScriptUtil:0x82040022:stack-long-immediate:32",
        "ParseTable",
    ),
    SelectorOperationRoute::new(
        0x8204FFF8,
        "selector-operation:_ScriptUtil:0x8204FFF8:stack-long-immediate:32",
        "InitDateCache",
    ),
    SelectorOperationRoute::new(
        0x8204FFFA,
        "selector-operation:_ScriptUtil:0x8204FFFA:stack-long-immediate:32",
        "IntlTokenize",
    ),
    SelectorOperationRoute::new(
        0x8208FFE0,
        "selector-operation:_ScriptUtil:0x8208FFE0:stack-long-immediate:32",
        "TruncString",
    ),
    SelectorOperationRoute::new(
        0x820C0026,
        "selector-operation:_ScriptUtil:0x820C0026:stack-long-immediate:32",
        "FindScriptRun",
    ),
    SelectorOperationRoute::new(
        0x820CFFDE,
        "selector-operation:_ScriptUtil:0x820CFFDE:stack-long-immediate:32",
        "TruncText",
    ),
    SelectorOperationRoute::new(
        0x820CFFE4,
        "selector-operation:_ScriptUtil:0x820CFFE4:stack-long-immediate:32",
        "ValidDate",
    ),
    SelectorOperationRoute::new(
        0x820CFFEC,
        "selector-operation:_ScriptUtil:0x820CFFEC:stack-long-immediate:32",
        "StringToFormatRec",
    ),
    SelectorOperationRoute::new(
        0x820EFFEE,
        "selector-operation:_ScriptUtil:0x820EFFEE:stack-long-immediate:32",
        "ToggleDate",
    ),
    SelectorOperationRoute::new(
        0x8210FFE6,
        "selector-operation:_ScriptUtil:0x8210FFE6:stack-long-immediate:32",
        "StringToExtended",
    ),
    SelectorOperationRoute::new(
        0x8210FFE8,
        "selector-operation:_ScriptUtil:0x8210FFE8:stack-long-immediate:32",
        "ExtendedToString",
    ),
    SelectorOperationRoute::new(
        0x8210FFEA,
        "selector-operation:_ScriptUtil:0x8210FFEA:stack-long-immediate:32",
        "FormatRecToString",
    ),
    SelectorOperationRoute::new(
        0x8214FFF4,
        "selector-operation:_ScriptUtil:0x8214FFF4:stack-long-immediate:32",
        "StringToTime",
    ),
    SelectorOperationRoute::new(
        0x8214FFF6,
        "selector-operation:_ScriptUtil:0x8214FFF6:stack-long-immediate:32",
        "StringToDate",
    ),
    SelectorOperationRoute::new(
        0x821CFFFE,
        "selector-operation:_ScriptUtil:0x821CFFFE:stack-long-immediate:32",
        "StyledLineBreak",
    ),
    SelectorOperationRoute::new(
        0x84080024,
        "selector-operation:_ScriptUtil:0x84080024:stack-long-immediate:32",
        "PortionText",
    ),
    SelectorOperationRoute::new(
        0x84080028,
        "selector-operation:_ScriptUtil:0x84080028:stack-long-immediate:32",
        "VisibleLength",
    ),
    SelectorOperationRoute::new(
        0xC012001A,
        "selector-operation:_ScriptUtil:0xC012001A:stack-long-immediate:32",
        "FindWordBreaks",
    ),
]
