// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0100,
        "selector-operation:_Pack11:0x0100:d0-low-word-immediate:16",
        "InitEditionPack",
    ),
    SelectorOperationRoute::new(
        0x0206,
        "selector-operation:_Pack11:0x0206:d0-low-word-immediate:16",
        "UnRegisterSection",
    ),
    SelectorOperationRoute::new(
        0x0208,
        "selector-operation:_Pack11:0x0208:d0-low-word-immediate:16",
        "IsRegisteredSection",
    ),
    SelectorOperationRoute::new(
        0x0210,
        "selector-operation:_Pack11:0x0210:d0-low-word-immediate:16",
        "DeleteEditionContainerFile",
    ),
    SelectorOperationRoute::new(
        0x0224,
        "selector-operation:_Pack11:0x0224:d0-low-word-immediate:16",
        "GoToPublisherSection",
    ),
    SelectorOperationRoute::new(
        0x0226,
        "selector-operation:_Pack11:0x0226:d0-low-word-immediate:16",
        "GetLastEditionContainerUsed",
    ),
    SelectorOperationRoute::new(
        0x022A,
        "selector-operation:_Pack11:0x022A:d0-low-word-immediate:16",
        "GetEditionOpenerProc",
    ),
    SelectorOperationRoute::new(
        0x022C,
        "selector-operation:_Pack11:0x022C:d0-low-word-immediate:16",
        "SetEditionOpenerProc",
    ),
    SelectorOperationRoute::new(
        0x0232,
        "selector-operation:_Pack11:0x0232:d0-low-word-immediate:16",
        "NewSubscriberDialog",
    ),
    SelectorOperationRoute::new(
        0x0236,
        "selector-operation:_Pack11:0x0236:d0-low-word-immediate:16",
        "NewPublisherDialog",
    ),
    SelectorOperationRoute::new(
        0x023A,
        "selector-operation:_Pack11:0x023A:d0-low-word-immediate:16",
        "SectionOptionsDialog",
    ),
    SelectorOperationRoute::new(
        0x0316,
        "selector-operation:_Pack11:0x0316:d0-low-word-immediate:16",
        "CloseEdition",
    ),
    SelectorOperationRoute::new(
        0x040C,
        "selector-operation:_Pack11:0x040C:d0-low-word-immediate:16",
        "AssociateSection",
    ),
    SelectorOperationRoute::new(
        0x0412,
        "selector-operation:_Pack11:0x0412:d0-low-word-immediate:16",
        "OpenEdition",
    ),
    SelectorOperationRoute::new(
        0x0422,
        "selector-operation:_Pack11:0x0422:d0-low-word-immediate:16",
        "GetEditionInfo",
    ),
    SelectorOperationRoute::new(
        0x050E,
        "selector-operation:_Pack11:0x050E:d0-low-word-immediate:16",
        "CreateEditionContainerFile",
    ),
    SelectorOperationRoute::new(
        0x052E,
        "selector-operation:_Pack11:0x052E:d0-low-word-immediate:16",
        "CallEditionOpenerProc",
    ),
    SelectorOperationRoute::new(
        0x0530,
        "selector-operation:_Pack11:0x0530:d0-low-word-immediate:16",
        "CallFormatIOProc",
    ),
    SelectorOperationRoute::new(
        0x0604,
        "selector-operation:_Pack11:0x0604:d0-low-word-immediate:16",
        "RegisterSection",
    ),
    SelectorOperationRoute::new(
        0x0618,
        "selector-operation:_Pack11:0x0618:d0-low-word-immediate:16",
        "EditionHasFormat",
    ),
    SelectorOperationRoute::new(
        0x061E,
        "selector-operation:_Pack11:0x061E:d0-low-word-immediate:16",
        "GetEditionFormatMark",
    ),
    SelectorOperationRoute::new(
        0x0620,
        "selector-operation:_Pack11:0x0620:d0-low-word-immediate:16",
        "SetEditionFormatMark",
    ),
    SelectorOperationRoute::new(
        0x0814,
        "selector-operation:_Pack11:0x0814:d0-low-word-immediate:16",
        "OpenNewEdition",
    ),
    SelectorOperationRoute::new(
        0x081A,
        "selector-operation:_Pack11:0x081A:d0-low-word-immediate:16",
        "ReadEdition",
    ),
    SelectorOperationRoute::new(
        0x081C,
        "selector-operation:_Pack11:0x081C:d0-low-word-immediate:16",
        "WriteEdition",
    ),
    SelectorOperationRoute::new(
        0x0A02,
        "selector-operation:_Pack11:0x0A02:d0-low-word-immediate:16",
        "NewSection",
    ),
    SelectorOperationRoute::new(
        0x0A28,
        "selector-operation:_Pack11:0x0A28:d0-low-word-immediate:16",
        "GetStandardFormats",
    ),
    SelectorOperationRoute::new(
        0x0B34,
        "selector-operation:_Pack11:0x0B34:d0-low-word-immediate:16",
        "NewSubscriberExpDialog",
    ),
    SelectorOperationRoute::new(
        0x0B38,
        "selector-operation:_Pack11:0x0B38:d0-low-word-immediate:16",
        "NewPublisherExpDialog",
    ),
    SelectorOperationRoute::new(
        0x0B3C,
        "selector-operation:_Pack11:0x0B3C:d0-low-word-immediate:16",
        "SectionOptionsExpDialog",
    ),
]
