// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0002,
        "selector-operation:_Pack14:0x0002:d0-low-word-immediate:16",
        "HMRemoveBalloon",
    ),
    SelectorOperationRoute::new(
        0x0003,
        "selector-operation:_Pack14:0x0003:d0-low-word-immediate:16",
        "HMGetBalloons",
    ),
    SelectorOperationRoute::new(
        0x0007,
        "selector-operation:_Pack14:0x0007:d0-low-word-immediate:16",
        "HMIsBalloon",
    ),
    SelectorOperationRoute::new(
        0x0104,
        "selector-operation:_Pack14:0x0104:d0-low-word-immediate:16",
        "HMSetBalloons",
    ),
    SelectorOperationRoute::new(
        0x0108,
        "selector-operation:_Pack14:0x0108:d0-low-word-immediate:16",
        "HMSetFont",
    ),
    SelectorOperationRoute::new(
        0x0109,
        "selector-operation:_Pack14:0x0109:d0-low-word-immediate:16",
        "HMSetFontSize",
    ),
    SelectorOperationRoute::new(
        0x010C,
        "selector-operation:_Pack14:0x010C:d0-low-word-immediate:16",
        "HMSetDialogResID",
    ),
    SelectorOperationRoute::new(
        0x0200,
        "selector-operation:_Pack14:0x0200:d0-low-word-immediate:16",
        "HMGetHelpMenuHandle",
    ),
    SelectorOperationRoute::new(
        0x020A,
        "selector-operation:_Pack14:0x020A:d0-low-word-immediate:16",
        "HMGetFont",
    ),
    SelectorOperationRoute::new(
        0x020B,
        "selector-operation:_Pack14:0x020B:d0-low-word-immediate:16",
        "HMGetFontSize",
    ),
    SelectorOperationRoute::new(
        0x020D,
        "selector-operation:_Pack14:0x020D:d0-low-word-immediate:16",
        "HMSetMenuResID",
    ),
    SelectorOperationRoute::new(
        0x0213,
        "selector-operation:_Pack14:0x0213:d0-low-word-immediate:16",
        "HMGetDialogResID",
    ),
    SelectorOperationRoute::new(
        0x0215,
        "selector-operation:_Pack14:0x0215:d0-low-word-immediate:16",
        "HMGetBalloonWindow",
    ),
    SelectorOperationRoute::new(
        0x0314,
        "selector-operation:_Pack14:0x0314:d0-low-word-immediate:16",
        "HMGetMenuResID",
    ),
    SelectorOperationRoute::new(
        0x040E,
        "selector-operation:_Pack14:0x040E:d0-low-word-immediate:16",
        "HMBalloonRect",
    ),
    SelectorOperationRoute::new(
        0x040F,
        "selector-operation:_Pack14:0x040F:d0-low-word-immediate:16",
        "HMBalloonPict",
    ),
    SelectorOperationRoute::new(
        0x0410,
        "selector-operation:_Pack14:0x0410:d0-low-word-immediate:16",
        "HMScanTemplateItems",
    ),
    SelectorOperationRoute::new(
        0x0711,
        "selector-operation:_Pack14:0x0711:d0-low-word-immediate:16",
        "HMExtractHelpMsg",
    ),
    SelectorOperationRoute::new(
        0x0B01,
        "selector-operation:_Pack14:0x0B01:d0-low-word-immediate:16",
        "HMShowBalloon",
    ),
    SelectorOperationRoute::new(
        0x0E05,
        "selector-operation:_Pack14:0x0E05:d0-low-word-immediate:16",
        "HMShowMenuBalloon",
    ),
    SelectorOperationRoute::new(
        0x1306,
        "selector-operation:_Pack14:0x1306:d0-low-word-immediate:16",
        "HMGetIndHelpMsg",
    ),
]
