// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0000,
        "selector-operation:_DebugUtil:0x0000:d0-moveq-immediate:8",
        "DebuggerGetMax",
    ),
    SelectorOperationRoute::new(
        0x0001,
        "selector-operation:_DebugUtil:0x0001:d0-moveq-immediate:8",
        "DebuggerEnter",
    ),
    SelectorOperationRoute::new(
        0x0002,
        "selector-operation:_DebugUtil:0x0002:d0-moveq-immediate:8",
        "DebuggerExit",
    ),
    SelectorOperationRoute::new(
        0x0003,
        "selector-operation:_DebugUtil:0x0003:d0-moveq-immediate:8",
        "DebuggerPoll",
    ),
    SelectorOperationRoute::new(
        0x0004,
        "selector-operation:_DebugUtil:0x0004:d0-moveq-immediate:8",
        "GetPageState",
    ),
    SelectorOperationRoute::new(
        0x0005,
        "selector-operation:_DebugUtil:0x0005:d0-moveq-immediate:8",
        "PageFaultFatal",
    ),
    SelectorOperationRoute::new(
        0x0006,
        "selector-operation:_DebugUtil:0x0006:d0-moveq-immediate:8",
        "DebuggerLockMemory",
    ),
    SelectorOperationRoute::new(
        0x0007,
        "selector-operation:_DebugUtil:0x0007:d0-moveq-immediate:8",
        "DebuggerUnlockMemory",
    ),
    SelectorOperationRoute::new(
        0x0008,
        "selector-operation:_DebugUtil:0x0008:d0-moveq-immediate:8",
        "EnterSupervisorMode",
    ),
]
