// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0000,
        "selector-operation:_Pack0:0x0000:stack-word-zero:16",
        "LActivate",
    ),
    SelectorOperationRoute::new(
        0x0004,
        "selector-operation:_Pack0:0x0004:stack-word-immediate:16",
        "LAddColumn",
    ),
    SelectorOperationRoute::new(
        0x0008,
        "selector-operation:_Pack0:0x0008:stack-word-immediate:16",
        "LAddRow",
    ),
    SelectorOperationRoute::new(
        0x000C,
        "selector-operation:_Pack0:0x000C:stack-word-immediate:16",
        "LAddToCell",
    ),
    SelectorOperationRoute::new(
        0x0010,
        "selector-operation:_Pack0:0x0010:stack-word-immediate:16",
        "LAutoScroll",
    ),
    SelectorOperationRoute::new(
        0x0014,
        "selector-operation:_Pack0:0x0014:stack-word-immediate:16",
        "LCellSize",
    ),
    SelectorOperationRoute::new(
        0x0018,
        "selector-operation:_Pack0:0x0018:stack-word-immediate:16",
        "LClick",
    ),
    SelectorOperationRoute::new(
        0x001C,
        "selector-operation:_Pack0:0x001C:stack-word-immediate:16",
        "LClrCell",
    ),
    SelectorOperationRoute::new(
        0x0020,
        "selector-operation:_Pack0:0x0020:stack-word-immediate:16",
        "LDelColumn",
    ),
    SelectorOperationRoute::new(
        0x0024,
        "selector-operation:_Pack0:0x0024:stack-word-immediate:16",
        "LDelRow",
    ),
    SelectorOperationRoute::new(
        0x0028,
        "selector-operation:_Pack0:0x0028:stack-word-immediate:16",
        "LDispose",
    ),
    SelectorOperationRoute::new(
        0x002C,
        "selector-operation:_Pack0:0x002C:stack-word-immediate:16",
        "LSetDrawingMode",
    ),
    SelectorOperationRoute::new(
        0x0030,
        "selector-operation:_Pack0:0x0030:stack-word-immediate:16",
        "LDraw",
    ),
    SelectorOperationRoute::new(
        0x0034,
        "selector-operation:_Pack0:0x0034:stack-word-immediate:16",
        "LGetCellDataLocation",
    ),
    SelectorOperationRoute::new(
        0x0038,
        "selector-operation:_Pack0:0x0038:stack-word-immediate:16",
        "LGetCell",
    ),
    SelectorOperationRoute::new(
        0x003C,
        "selector-operation:_Pack0:0x003C:stack-word-immediate:16",
        "LGetSelect",
    ),
    SelectorOperationRoute::new(
        0x0040,
        "selector-operation:_Pack0:0x0040:stack-word-immediate:16",
        "LLastClick",
    ),
    SelectorOperationRoute::new(
        0x0044,
        "selector-operation:_Pack0:0x0044:stack-word-immediate:16",
        "LNew",
    ),
    SelectorOperationRoute::new(
        0x0048,
        "selector-operation:_Pack0:0x0048:stack-word-immediate:16",
        "LNextCell",
    ),
    SelectorOperationRoute::new(
        0x004C,
        "selector-operation:_Pack0:0x004C:stack-word-immediate:16",
        "LRect",
    ),
    SelectorOperationRoute::new(
        0x0050,
        "selector-operation:_Pack0:0x0050:stack-word-immediate:16",
        "LScroll",
    ),
    SelectorOperationRoute::new(
        0x0054,
        "selector-operation:_Pack0:0x0054:stack-word-immediate:16",
        "LSearch",
    ),
    SelectorOperationRoute::new(
        0x0058,
        "selector-operation:_Pack0:0x0058:stack-word-immediate:16",
        "LSetCell",
    ),
    SelectorOperationRoute::new(
        0x005C,
        "selector-operation:_Pack0:0x005C:stack-word-immediate:16",
        "LSetSelect",
    ),
    SelectorOperationRoute::new(
        0x0060,
        "selector-operation:_Pack0:0x0060:stack-word-immediate:16",
        "LSize",
    ),
    SelectorOperationRoute::new(
        0x0064,
        "selector-operation:_Pack0:0x0064:stack-word-immediate:16",
        "LUpdate",
    ),
]
