// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0001,
        "selector-operation:_ComponentDispatch:0x0001:d0-moveq-immediate:8",
        "RegisterComponent",
    ),
    SelectorOperationRoute::new(
        0x0002,
        "selector-operation:_ComponentDispatch:0x0002:d0-moveq-immediate:8",
        "UnregisterComponent",
    ),
    SelectorOperationRoute::new(
        0x0003,
        "selector-operation:_ComponentDispatch:0x0003:d0-moveq-immediate:8",
        "CountComponents",
    ),
    SelectorOperationRoute::new(
        0x0004,
        "selector-operation:_ComponentDispatch:0x0004:d0-moveq-immediate:8",
        "FindNextComponent",
    ),
    SelectorOperationRoute::new(
        0x0005,
        "selector-operation:_ComponentDispatch:0x0005:d0-moveq-immediate:8",
        "GetComponentInfo",
    ),
    SelectorOperationRoute::new(
        0x0006,
        "selector-operation:_ComponentDispatch:0x0006:d0-moveq-immediate:8",
        "GetComponentListModSeed",
    ),
    SelectorOperationRoute::new(
        0x0007,
        "selector-operation:_ComponentDispatch:0x0007:d0-moveq-immediate:8",
        "OpenComponent",
    ),
    SelectorOperationRoute::new(
        0x0008,
        "selector-operation:_ComponentDispatch:0x0008:d0-moveq-immediate:8",
        "CloseComponent",
    ),
    SelectorOperationRoute::new(
        0x000A,
        "selector-operation:_ComponentDispatch:0x000A:d0-moveq-immediate:8",
        "GetComponentInstanceError",
    ),
    SelectorOperationRoute::new(
        0x000B,
        "selector-operation:_ComponentDispatch:0x000B:d0-moveq-immediate:8",
        "SetComponentInstanceError",
    ),
    SelectorOperationRoute::new(
        0x000C,
        "selector-operation:_ComponentDispatch:0x000C:d0-moveq-immediate:8",
        "GetComponentInstanceStorage",
    ),
    SelectorOperationRoute::new(
        0x000D,
        "selector-operation:_ComponentDispatch:0x000D:d0-moveq-immediate:8",
        "SetComponentInstanceStorage",
    ),
    SelectorOperationRoute::new(
        0x000E,
        "selector-operation:_ComponentDispatch:0x000E:d0-moveq-immediate:8",
        "GetComponentInstanceA5",
    ),
    SelectorOperationRoute::new(
        0x000F,
        "selector-operation:_ComponentDispatch:0x000F:d0-moveq-immediate:8",
        "SetComponentInstanceA5",
    ),
    SelectorOperationRoute::new(
        0x0010,
        "selector-operation:_ComponentDispatch:0x0010:d0-moveq-immediate:8",
        "GetComponentRefcon",
    ),
    SelectorOperationRoute::new(
        0x0011,
        "selector-operation:_ComponentDispatch:0x0011:d0-moveq-immediate:8",
        "SetComponentRefcon",
    ),
    SelectorOperationRoute::new(
        0x0012,
        "selector-operation:_ComponentDispatch:0x0012:d0-moveq-immediate:8",
        "RegisterComponentResource",
    ),
    SelectorOperationRoute::new(
        0x0013,
        "selector-operation:_ComponentDispatch:0x0013:d0-moveq-immediate:8",
        "CountComponentInstances",
    ),
    SelectorOperationRoute::new(
        0x0014,
        "selector-operation:_ComponentDispatch:0x0014:d0-moveq-immediate:8",
        "RegisterComponentResourceFile",
    ),
    SelectorOperationRoute::new(
        0x0015,
        "selector-operation:_ComponentDispatch:0x0015:d0-moveq-immediate:8",
        "OpenComponentResFile",
    ),
    SelectorOperationRoute::new(
        0x0018,
        "selector-operation:_ComponentDispatch:0x0018:d0-moveq-immediate:8",
        "CloseComponentResFile",
    ),
    SelectorOperationRoute::new(
        0x001C,
        "selector-operation:_ComponentDispatch:0x001C:d0-moveq-immediate:8",
        "CaptureComponent",
    ),
    SelectorOperationRoute::new(
        0x001D,
        "selector-operation:_ComponentDispatch:0x001D:d0-moveq-immediate:8",
        "UncaptureComponent",
    ),
    SelectorOperationRoute::new(
        0x001E,
        "selector-operation:_ComponentDispatch:0x001E:d0-moveq-immediate:8",
        "SetDefaultComponent",
    ),
    SelectorOperationRoute::new(
        0x0021,
        "selector-operation:_ComponentDispatch:0x0021:d0-moveq-immediate:8",
        "OpenDefaultComponent",
    ),
    SelectorOperationRoute::new(
        0x0024,
        "selector-operation:_ComponentDispatch:0x0024:d0-moveq-immediate:8",
        "DelegateComponentCall",
    ),
]
