// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0100,
        "selector-operation:_Pack13:0x0100:d0-low-word-immediate:16",
        "InitDBPack",
    ),
    SelectorOperationRoute::new(
        0x020E,
        "selector-operation:_Pack13:0x020E:d0-low-word-immediate:16",
        "DBKill",
    ),
    SelectorOperationRoute::new(
        0x0210,
        "selector-operation:_Pack13:0x0210:d0-low-word-immediate:16",
        "DBDisposeQuery",
    ),
    SelectorOperationRoute::new(
        0x0215,
        "selector-operation:_Pack13:0x0215:d0-low-word-immediate:16",
        "DBRemoveResultHandler",
    ),
    SelectorOperationRoute::new(
        0x030F,
        "selector-operation:_Pack13:0x030F:d0-low-word-immediate:16",
        "DBGetNewQuery",
    ),
    SelectorOperationRoute::new(
        0x0403,
        "selector-operation:_Pack13:0x0403:d0-low-word-immediate:16",
        "DBEnd",
    ),
    SelectorOperationRoute::new(
        0x0408,
        "selector-operation:_Pack13:0x0408:d0-low-word-immediate:16",
        "DBExec",
    ),
    SelectorOperationRoute::new(
        0x0409,
        "selector-operation:_Pack13:0x0409:d0-low-word-immediate:16",
        "DBState",
    ),
    SelectorOperationRoute::new(
        0x040D,
        "selector-operation:_Pack13:0x040D:d0-low-word-immediate:16",
        "DBUnGetItem",
    ),
    SelectorOperationRoute::new(
        0x0413,
        "selector-operation:_Pack13:0x0413:d0-low-word-immediate:16",
        "DBResultsToText",
    ),
    SelectorOperationRoute::new(
        0x050B,
        "selector-operation:_Pack13:0x050B:d0-low-word-immediate:16",
        "DBBreak",
    ),
    SelectorOperationRoute::new(
        0x0514,
        "selector-operation:_Pack13:0x0514:d0-low-word-immediate:16",
        "DBInstallResultHandler",
    ),
    SelectorOperationRoute::new(
        0x0516,
        "selector-operation:_Pack13:0x0516:d0-low-word-immediate:16",
        "DBGetResultHandler",
    ),
    SelectorOperationRoute::new(
        0x0605,
        "selector-operation:_Pack13:0x0605:d0-low-word-immediate:16",
        "DBGetSessionNum",
    ),
    SelectorOperationRoute::new(
        0x0706,
        "selector-operation:_Pack13:0x0706:d0-low-word-immediate:16",
        "DBSend",
    ),
    SelectorOperationRoute::new(
        0x0811,
        "selector-operation:_Pack13:0x0811:d0-low-word-immediate:16",
        "DBStartQuery",
    ),
    SelectorOperationRoute::new(
        0x0A12,
        "selector-operation:_Pack13:0x0A12:d0-low-word-immediate:16",
        "DBGetQueryResults",
    ),
    SelectorOperationRoute::new(
        0x0B07,
        "selector-operation:_Pack13:0x0B07:d0-low-word-immediate:16",
        "DBSendItem",
    ),
    SelectorOperationRoute::new(
        0x0E02,
        "selector-operation:_Pack13:0x0E02:d0-low-word-immediate:16",
        "DBInit",
    ),
    SelectorOperationRoute::new(
        0x0E0A,
        "selector-operation:_Pack13:0x0E0A:d0-low-word-immediate:16",
        "DBGetErr",
    ),
    SelectorOperationRoute::new(
        0x100C,
        "selector-operation:_Pack13:0x100C:d0-low-word-immediate:16",
        "DBGetItem",
    ),
    SelectorOperationRoute::new(
        0x1704,
        "selector-operation:_Pack13:0x1704:d0-low-word-immediate:16",
        "DBGetConnInfo",
    ),
]
