// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0015,
        "selector-operation:_OSDispatch:0x0015:stack-word-immediate:16",
        "TempMaxMem",
    ),
    SelectorOperationRoute::new(
        0x0016,
        "selector-operation:_OSDispatch:0x0016:stack-word-immediate:16",
        "TempTopMem",
    ),
    SelectorOperationRoute::new(
        0x0018,
        "selector-operation:_OSDispatch:0x0018:stack-word-immediate:16",
        "TempFreeMem",
    ),
    SelectorOperationRoute::new(
        0x001D,
        "selector-operation:_OSDispatch:0x001D:stack-word-immediate:16",
        "TempNewHandle",
    ),
    SelectorOperationRoute::new(
        0x001E,
        "selector-operation:_OSDispatch:0x001E:stack-word-immediate:16",
        "TempHLock",
    ),
    SelectorOperationRoute::new(
        0x001F,
        "selector-operation:_OSDispatch:0x001F:stack-word-immediate:16",
        "TempHUnlock",
    ),
    SelectorOperationRoute::new(
        0x0020,
        "selector-operation:_OSDispatch:0x0020:stack-word-immediate:16",
        "TempDisposeHandle",
    ),
    SelectorOperationRoute::new(
        0x0033,
        "selector-operation:_OSDispatch:0x0033:stack-word-immediate:16",
        "AcceptHighLevelEvent",
    ),
    SelectorOperationRoute::new(
        0x0034,
        "selector-operation:_OSDispatch:0x0034:stack-word-immediate:16",
        "PostHighLevelEvent",
    ),
    SelectorOperationRoute::new(
        0x0035,
        "selector-operation:_OSDispatch:0x0035:stack-word-immediate:16",
        "GetProcessSerialNumberFromPortName",
    ),
    SelectorOperationRoute::new(
        0x0036,
        "selector-operation:_OSDispatch:0x0036:stack-word-immediate:16",
        "LaunchDeskAccessory",
    ),
    SelectorOperationRoute::new(
        0x0038,
        "selector-operation:_OSDispatch:0x0038:stack-word-immediate:16",
        "GetNextProcess",
    ),
    SelectorOperationRoute::new(
        0x0039,
        "selector-operation:_OSDispatch:0x0039:stack-word-immediate:16",
        "GetFrontProcess",
    ),
    SelectorOperationRoute::new(
        0x003A,
        "selector-operation:_OSDispatch:0x003A:stack-word-immediate:16",
        "GetProcessInformation",
    ),
    SelectorOperationRoute::new(
        0x003B,
        "selector-operation:_OSDispatch:0x003B:stack-word-immediate:16",
        "SetFrontProcess",
    ),
    SelectorOperationRoute::new(
        0x003C,
        "selector-operation:_OSDispatch:0x003C:stack-word-immediate:16",
        "WakeUpProcess",
    ),
    SelectorOperationRoute::new(
        0x003D,
        "selector-operation:_OSDispatch:0x003D:stack-word-immediate:16",
        "SameProcess",
    ),
    SelectorOperationRoute::new(
        0x0045,
        "selector-operation:_OSDispatch:0x0045:stack-word-immediate:16",
        "GetSpecificHighLevelEvent",
    ),
    SelectorOperationRoute::new(
        0x0046,
        "selector-operation:_OSDispatch:0x0046:stack-word-immediate:16",
        "GetPortNameFromProcessSerialNumber",
    ),
]
