// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x011E,
        "selector-operation:_Pack8:0x011E:d0-low-word-immediate:16",
        "AESetInteractionAllowed",
    ),
    SelectorOperationRoute::new(
        0x0204,
        "selector-operation:_Pack8:0x0204:d0-low-word-immediate:16",
        "AEDisposeDesc",
    ),
    SelectorOperationRoute::new(
        0x0219,
        "selector-operation:_Pack8:0x0219:d0-low-word-immediate:16",
        "AEResetTimer",
    ),
    SelectorOperationRoute::new(
        0x021A,
        "selector-operation:_Pack8:0x021A:d0-low-word-immediate:16",
        "AEGetTheCurrentEvent",
    ),
    SelectorOperationRoute::new(
        0x021B,
        "selector-operation:_Pack8:0x021B:d0-low-word-immediate:16",
        "AEProcessAppleEvent",
    ),
    SelectorOperationRoute::new(
        0x021D,
        "selector-operation:_Pack8:0x021D:d0-low-word-immediate:16",
        "AEGetInteractionAllowed",
    ),
    SelectorOperationRoute::new(
        0x022B,
        "selector-operation:_Pack8:0x022B:d0-low-word-immediate:16",
        "AESuspendTheCurrentEvent",
    ),
    SelectorOperationRoute::new(
        0x022C,
        "selector-operation:_Pack8:0x022C:d0-low-word-immediate:16",
        "AESetTheCurrentEvent",
    ),
    SelectorOperationRoute::new(
        0x023A,
        "selector-operation:_Pack8:0x023A:d0-low-word-immediate:16",
        "AEDisposeToken",
    ),
    SelectorOperationRoute::new(
        0x0405,
        "selector-operation:_Pack8:0x0405:d0-low-word-immediate:16",
        "AEDuplicateDesc",
    ),
    SelectorOperationRoute::new(
        0x0407,
        "selector-operation:_Pack8:0x0407:d0-low-word-immediate:16",
        "AECountItems",
    ),
    SelectorOperationRoute::new(
        0x040E,
        "selector-operation:_Pack8:0x040E:d0-low-word-immediate:16",
        "AEDeleteItem",
    ),
    SelectorOperationRoute::new(
        0x0413,
        "selector-operation:_Pack8:0x0413:d0-low-word-immediate:16",
        "AEDeleteParam",
    ),
    SelectorOperationRoute::new(
        0x0441,
        "selector-operation:_Pack8:0x0441:d0-low-word-immediate:16",
        "AEManagerInfo",
    ),
    SelectorOperationRoute::new(
        0x0500,
        "selector-operation:_Pack8:0x0500:d0-low-word-immediate:16",
        "AEInstallSpecialHandler",
    ),
    SelectorOperationRoute::new(
        0x0501,
        "selector-operation:_Pack8:0x0501:d0-low-word-immediate:16",
        "AERemoveSpecialHandler",
    ),
    SelectorOperationRoute::new(
        0x052D,
        "selector-operation:_Pack8:0x052D:d0-low-word-immediate:16",
        "AEGetSpecialHandler",
    ),
    SelectorOperationRoute::new(
        0x0536,
        "selector-operation:_Pack8:0x0536:d0-low-word-immediate:16",
        "AEResolve",
    ),
    SelectorOperationRoute::new(
        0x0603,
        "selector-operation:_Pack8:0x0603:d0-low-word-immediate:16",
        "AECoerceDesc",
    ),
    SelectorOperationRoute::new(
        0x0609,
        "selector-operation:_Pack8:0x0609:d0-low-word-immediate:16",
        "AEPutDesc",
    ),
    SelectorOperationRoute::new(
        0x0610,
        "selector-operation:_Pack8:0x0610:d0-low-word-immediate:16",
        "AEPutParamDesc",
    ),
    SelectorOperationRoute::new(
        0x061C,
        "selector-operation:_Pack8:0x061C:d0-low-word-immediate:16",
        "AEInteractWithUser",
    ),
    SelectorOperationRoute::new(
        0x0627,
        "selector-operation:_Pack8:0x0627:d0-low-word-immediate:16",
        "AEPutAttributeDesc",
    ),
    SelectorOperationRoute::new(
        0x0706,
        "selector-operation:_Pack8:0x0706:d0-low-word-immediate:16",
        "AECreateList",
    ),
    SelectorOperationRoute::new(
        0x0720,
        "selector-operation:_Pack8:0x0720:d0-low-word-immediate:16",
        "AERemoveEventHandler",
    ),
    SelectorOperationRoute::new(
        0x0723,
        "selector-operation:_Pack8:0x0723:d0-low-word-immediate:16",
        "AERemoveCoercionHandler",
    ),
    SelectorOperationRoute::new(
        0x0738,
        "selector-operation:_Pack8:0x0738:d0-low-word-immediate:16",
        "AERemoveObjectAccessor",
    ),
    SelectorOperationRoute::new(
        0x0812,
        "selector-operation:_Pack8:0x0812:d0-low-word-immediate:16",
        "AEGetParamDesc",
    ),
    SelectorOperationRoute::new(
        0x0818,
        "selector-operation:_Pack8:0x0818:d0-low-word-immediate:16",
        "AEResumeTheCurrentEvent",
    ),
    SelectorOperationRoute::new(
        0x0825,
        "selector-operation:_Pack8:0x0825:d0-low-word-immediate:16",
        "AECreateDesc",
    ),
    SelectorOperationRoute::new(
        0x0826,
        "selector-operation:_Pack8:0x0826:d0-low-word-immediate:16",
        "AEGetAttributeDesc",
    ),
    SelectorOperationRoute::new(
        0x0828,
        "selector-operation:_Pack8:0x0828:d0-low-word-immediate:16",
        "AESizeOfAttribute",
    ),
    SelectorOperationRoute::new(
        0x0829,
        "selector-operation:_Pack8:0x0829:d0-low-word-immediate:16",
        "AESizeOfParam",
    ),
    SelectorOperationRoute::new(
        0x082A,
        "selector-operation:_Pack8:0x082A:d0-low-word-immediate:16",
        "AESizeOfNthItem",
    ),
    SelectorOperationRoute::new(
        0x091F,
        "selector-operation:_Pack8:0x091F:d0-low-word-immediate:16",
        "AEInstallEventHandler",
    ),
    SelectorOperationRoute::new(
        0x0921,
        "selector-operation:_Pack8:0x0921:d0-low-word-immediate:16",
        "AEGetEventHandler",
    ),
    SelectorOperationRoute::new(
        0x0937,
        "selector-operation:_Pack8:0x0937:d0-low-word-immediate:16",
        "AEInstallObjectAccessor",
    ),
    SelectorOperationRoute::new(
        0x0939,
        "selector-operation:_Pack8:0x0939:d0-low-word-immediate:16",
        "AEGetObjectAccessor",
    ),
    SelectorOperationRoute::new(
        0x0A02,
        "selector-operation:_Pack8:0x0A02:d0-low-word-immediate:16",
        "AECoercePtr",
    ),
    SelectorOperationRoute::new(
        0x0A08,
        "selector-operation:_Pack8:0x0A08:d0-low-word-immediate:16",
        "AEPutPtr",
    ),
    SelectorOperationRoute::new(
        0x0A0B,
        "selector-operation:_Pack8:0x0A0B:d0-low-word-immediate:16",
        "AEGetNthDesc",
    ),
    SelectorOperationRoute::new(
        0x0A0F,
        "selector-operation:_Pack8:0x0A0F:d0-low-word-immediate:16",
        "AEPutParamPtr",
    ),
    SelectorOperationRoute::new(
        0x0A16,
        "selector-operation:_Pack8:0x0A16:d0-low-word-immediate:16",
        "AEPutAttributePtr",
    ),
    SelectorOperationRoute::new(
        0x0A22,
        "selector-operation:_Pack8:0x0A22:d0-low-word-immediate:16",
        "AEInstallCoercionHandler",
    ),
    SelectorOperationRoute::new(
        0x0B0D,
        "selector-operation:_Pack8:0x0B0D:d0-low-word-immediate:16",
        "AEPutArray",
    ),
    SelectorOperationRoute::new(
        0x0B14,
        "selector-operation:_Pack8:0x0B14:d0-low-word-immediate:16",
        "AECreateAppleEvent",
    ),
    SelectorOperationRoute::new(
        0x0B24,
        "selector-operation:_Pack8:0x0B24:d0-low-word-immediate:16",
        "AEGetCoercionHandler",
    ),
    SelectorOperationRoute::new(
        0x0C3B,
        "selector-operation:_Pack8:0x0C3B:d0-low-word-immediate:16",
        "AECallObjectAccessor",
    ),
    SelectorOperationRoute::new(
        0x0D0C,
        "selector-operation:_Pack8:0x0D0C:d0-low-word-immediate:16",
        "AEGetArray",
    ),
    SelectorOperationRoute::new(
        0x0D17,
        "selector-operation:_Pack8:0x0D17:d0-low-word-immediate:16",
        "AESend",
    ),
    SelectorOperationRoute::new(
        0x0E11,
        "selector-operation:_Pack8:0x0E11:d0-low-word-immediate:16",
        "AEGetParamPtr",
    ),
    SelectorOperationRoute::new(
        0x0E15,
        "selector-operation:_Pack8:0x0E15:d0-low-word-immediate:16",
        "AEGetAttributePtr",
    ),
    SelectorOperationRoute::new(
        0x0E35,
        "selector-operation:_Pack8:0x0E35:d0-low-word-immediate:16",
        "AESetObjectCallbacks",
    ),
    SelectorOperationRoute::new(
        0x100A,
        "selector-operation:_Pack8:0x100A:d0-low-word-immediate:16",
        "AEGetNthPtr",
    ),
]
