// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0000,
        "selector-operation:_PowerMgrDispatch:0x0000:d0-moveq-immediate:8",
        "PMSelectorCount",
    ),
    SelectorOperationRoute::new(
        0x0001,
        "selector-operation:_PowerMgrDispatch:0x0001:d0-moveq-immediate:8",
        "PMFeatures",
    ),
    SelectorOperationRoute::new(
        0x0002,
        "selector-operation:_PowerMgrDispatch:0x0002:d0-moveq-immediate:8",
        "GetSleepTimeout",
    ),
    SelectorOperationRoute::new(
        0x0003,
        "selector-operation:_PowerMgrDispatch:0x0003:d0-low-word-immediate:16",
        "SetSleepTimeout",
    ),
    SelectorOperationRoute::new(
        0x0004,
        "selector-operation:_PowerMgrDispatch:0x0004:d0-moveq-immediate:8",
        "GetHardDiskTimeout",
    ),
    SelectorOperationRoute::new(
        0x0005,
        "selector-operation:_PowerMgrDispatch:0x0005:d0-low-word-immediate:16",
        "SetHardDiskTimeout",
    ),
    SelectorOperationRoute::new(
        0x0006,
        "selector-operation:_PowerMgrDispatch:0x0006:d0-moveq-immediate:8",
        "HardDiskPowered",
    ),
    SelectorOperationRoute::new(
        0x0007,
        "selector-operation:_PowerMgrDispatch:0x0007:d0-moveq-immediate:8",
        "SpinDownHardDisk",
    ),
    SelectorOperationRoute::new(
        0x0008,
        "selector-operation:_PowerMgrDispatch:0x0008:d0-moveq-immediate:8",
        "IsSpindownDisabled",
    ),
    SelectorOperationRoute::new(
        0x0009,
        "selector-operation:_PowerMgrDispatch:0x0009:d0-low-word-immediate:16",
        "SetSpindownDisable",
    ),
    SelectorOperationRoute::new(
        0x000A,
        "selector-operation:_PowerMgrDispatch:0x000A:d0-moveq-immediate:8",
        "HardDiskQInstall",
    ),
    SelectorOperationRoute::new(
        0x000B,
        "selector-operation:_PowerMgrDispatch:0x000B:d0-moveq-immediate:8",
        "HardDiskQRemove",
    ),
    SelectorOperationRoute::new(
        0x000C,
        "selector-operation:_PowerMgrDispatch:0x000C:d0-low-word-immediate:16",
        "GetScaledBatteryInfo",
    ),
    SelectorOperationRoute::new(
        0x000D,
        "selector-operation:_PowerMgrDispatch:0x000D:d0-low-word-immediate:16",
        "AutoSleepControl",
    ),
    SelectorOperationRoute::new(
        0x000E,
        "selector-operation:_PowerMgrDispatch:0x000E:d0-moveq-immediate:8",
        "GetIntModemInfo",
    ),
    SelectorOperationRoute::new(
        0x000F,
        "selector-operation:_PowerMgrDispatch:0x000F:d0-low-word-immediate:16",
        "SetIntModemState",
    ),
    SelectorOperationRoute::new(
        0x0010,
        "selector-operation:_PowerMgrDispatch:0x0010:d0-moveq-immediate:8",
        "MaximumProcessorSpeed",
    ),
    SelectorOperationRoute::new(
        0x0011,
        "selector-operation:_PowerMgrDispatch:0x0011:d0-moveq-immediate:8",
        "CurrentProcessorSpeed",
    ),
    SelectorOperationRoute::new(
        0x0012,
        "selector-operation:_PowerMgrDispatch:0x0012:d0-moveq-immediate:8",
        "FullProcessorSpeed",
    ),
    SelectorOperationRoute::new(
        0x0013,
        "selector-operation:_PowerMgrDispatch:0x0013:d0-low-word-immediate:16",
        "SetProcessorSpeed",
    ),
    SelectorOperationRoute::new(
        0x0014,
        "selector-operation:_PowerMgrDispatch:0x0014:d0-moveq-immediate:8",
        "GetSCSIDiskModeAddress",
    ),
    SelectorOperationRoute::new(
        0x0015,
        "selector-operation:_PowerMgrDispatch:0x0015:d0-low-word-immediate:16",
        "SetSCSIDiskModeAddress",
    ),
    SelectorOperationRoute::new(
        0x0016,
        "selector-operation:_PowerMgrDispatch:0x0016:d0-moveq-immediate:8",
        "GetWakeupTimer",
    ),
    SelectorOperationRoute::new(
        0x0017,
        "selector-operation:_PowerMgrDispatch:0x0017:d0-moveq-immediate:8",
        "SetWakeupTimer",
    ),
    SelectorOperationRoute::new(
        0x0018,
        "selector-operation:_PowerMgrDispatch:0x0018:d0-moveq-immediate:8",
        "IsProcessorCyclingEnabled",
    ),
    SelectorOperationRoute::new(
        0x0019,
        "selector-operation:_PowerMgrDispatch:0x0019:d0-low-word-immediate:16",
        "EnableProcessorCycling",
    ),
    SelectorOperationRoute::new(
        0x001A,
        "selector-operation:_PowerMgrDispatch:0x001A:d0-moveq-immediate:8",
        "BatteryCount",
    ),
    SelectorOperationRoute::new(
        0x001B,
        "selector-operation:_PowerMgrDispatch:0x001B:d0-low-word-immediate:16",
        "GetBatteryVoltage",
    ),
    SelectorOperationRoute::new(
        0x001C,
        "selector-operation:_PowerMgrDispatch:0x001C:d0-low-word-immediate:16",
        "GetBatteryTimes",
    ),
    SelectorOperationRoute::new(
        0x001D,
        "selector-operation:_PowerMgrDispatch:0x001D:d0-moveq-immediate:8",
        "GetDimmingTimeout",
    ),
    SelectorOperationRoute::new(
        0x001E,
        "selector-operation:_PowerMgrDispatch:0x001E:d0-low-word-immediate:16",
        "SetDimmingTimeout",
    ),
    SelectorOperationRoute::new(
        0x001F,
        "selector-operation:_PowerMgrDispatch:0x001F:d0-low-word-immediate:16",
        "DimmingControl",
    ),
    SelectorOperationRoute::new(
        0x0020,
        "selector-operation:_PowerMgrDispatch:0x0020:d0-moveq-immediate:8",
        "IsDimmingControlDisabled",
    ),
    SelectorOperationRoute::new(
        0x0021,
        "selector-operation:_PowerMgrDispatch:0x0021:d0-moveq-immediate:8",
        "IsAutoSlpControlDisabled",
    ),
]
