// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0000,
        "selector-operation:_SCSIDispatch:0x0000:stack-word-zero:16",
        "SCSIReset",
    ),
    SelectorOperationRoute::new(
        0x0001,
        "selector-operation:_SCSIDispatch:0x0001:stack-word-immediate:16",
        "SCSIGet",
    ),
    SelectorOperationRoute::new(
        0x0002,
        "selector-operation:_SCSIDispatch:0x0002:stack-word-immediate:16",
        "SCSISelect",
    ),
    SelectorOperationRoute::new(
        0x0003,
        "selector-operation:_SCSIDispatch:0x0003:stack-word-immediate:16",
        "SCSICmd",
    ),
    SelectorOperationRoute::new(
        0x0004,
        "selector-operation:_SCSIDispatch:0x0004:stack-word-immediate:16",
        "SCSIComplete",
    ),
    SelectorOperationRoute::new(
        0x0005,
        "selector-operation:_SCSIDispatch:0x0005:stack-word-immediate:16",
        "SCSIRead",
    ),
    SelectorOperationRoute::new(
        0x0006,
        "selector-operation:_SCSIDispatch:0x0006:stack-word-immediate:16",
        "SCSIWrite",
    ),
    SelectorOperationRoute::new(
        0x0008,
        "selector-operation:_SCSIDispatch:0x0008:stack-word-immediate:16",
        "SCSIRBlind",
    ),
    SelectorOperationRoute::new(
        0x0009,
        "selector-operation:_SCSIDispatch:0x0009:stack-word-immediate:16",
        "SCSIWBlind",
    ),
    SelectorOperationRoute::new(
        0x000A,
        "selector-operation:_SCSIDispatch:0x000A:stack-word-immediate:16",
        "SCSIStat",
    ),
    SelectorOperationRoute::new(
        0x000B,
        "selector-operation:_SCSIDispatch:0x000B:stack-word-immediate:16",
        "SCSISelAtn",
    ),
    SelectorOperationRoute::new(
        0x000C,
        "selector-operation:_SCSIDispatch:0x000C:stack-word-immediate:16",
        "SCSIMsgIn",
    ),
    SelectorOperationRoute::new(
        0x000D,
        "selector-operation:_SCSIDispatch:0x000D:stack-word-immediate:16",
        "SCSIMsgOut",
    ),
]
