// Generated selector-operation routes. Do not edit by hand.
[
    SelectorOperationRoute::new(
        0x0000,
        "selector-operation:_SlotManager:0x0000:d0-moveq-immediate:8",
        "SReadByte",
    ),
    SelectorOperationRoute::new(
        0x0001,
        "selector-operation:_SlotManager:0x0001:d0-moveq-immediate:8",
        "SReadWord",
    ),
    SelectorOperationRoute::new(
        0x0002,
        "selector-operation:_SlotManager:0x0002:d0-moveq-immediate:8",
        "SReadLong",
    ),
    SelectorOperationRoute::new(
        0x0003,
        "selector-operation:_SlotManager:0x0003:d0-moveq-immediate:8",
        "SGetCString",
    ),
    SelectorOperationRoute::new(
        0x0005,
        "selector-operation:_SlotManager:0x0005:d0-moveq-immediate:8",
        "SGetBlock",
    ),
    SelectorOperationRoute::new(
        0x0006,
        "selector-operation:_SlotManager:0x0006:d0-moveq-immediate:8",
        "SFindStruct",
    ),
    SelectorOperationRoute::new(
        0x0007,
        "selector-operation:_SlotManager:0x0007:d0-moveq-immediate:8",
        "SReadStruct",
    ),
    SelectorOperationRoute::new(
        0x0008,
        "selector-operation:_SlotManager:0x0008:d0-moveq-immediate:8",
        "SVersion",
    ),
    SelectorOperationRoute::new(
        0x0009,
        "selector-operation:_SlotManager:0x0009:d0-moveq-immediate:8",
        "SetSRsrcState",
    ),
    SelectorOperationRoute::new(
        0x000A,
        "selector-operation:_SlotManager:0x000A:d0-moveq-immediate:8",
        "InsertSRTRec",
    ),
    SelectorOperationRoute::new(
        0x000B,
        "selector-operation:_SlotManager:0x000B:d0-moveq-immediate:8",
        "SGetSRsrc",
    ),
    SelectorOperationRoute::new(
        0x000C,
        "selector-operation:_SlotManager:0x000C:d0-moveq-immediate:8",
        "SGetTypeSRsrc",
    ),
    SelectorOperationRoute::new(
        0x0010,
        "selector-operation:_SlotManager:0x0010:d0-moveq-immediate:8",
        "SReadInfo",
    ),
    SelectorOperationRoute::new(
        0x0011,
        "selector-operation:_SlotManager:0x0011:d0-moveq-immediate:8",
        "SReadPRAMRec",
    ),
    SelectorOperationRoute::new(
        0x0012,
        "selector-operation:_SlotManager:0x0012:d0-moveq-immediate:8",
        "SPutPRAMRec",
    ),
    SelectorOperationRoute::new(
        0x0013,
        "selector-operation:_SlotManager:0x0013:d0-moveq-immediate:8",
        "SReadFHeader",
    ),
    SelectorOperationRoute::new(
        0x0014,
        "selector-operation:_SlotManager:0x0014:d0-moveq-immediate:8",
        "SNextSRsrc",
    ),
    SelectorOperationRoute::new(
        0x0015,
        "selector-operation:_SlotManager:0x0015:d0-moveq-immediate:8",
        "SNextTypeSRsrc",
    ),
    SelectorOperationRoute::new(
        0x0016,
        "selector-operation:_SlotManager:0x0016:d0-moveq-immediate:8",
        "SRsrcInfo",
    ),
    SelectorOperationRoute::new(
        0x0018,
        "selector-operation:_SlotManager:0x0018:d0-moveq-immediate:8",
        "SCkCardStat",
    ),
    SelectorOperationRoute::new(
        0x0019,
        "selector-operation:_SlotManager:0x0019:d0-moveq-immediate:8",
        "SReadDrvrName",
    ),
    SelectorOperationRoute::new(
        0x001B,
        "selector-operation:_SlotManager:0x001B:d0-moveq-immediate:8",
        "SFindDevBase",
    ),
    SelectorOperationRoute::new(
        0x001C,
        "selector-operation:_SlotManager:0x001C:d0-moveq-immediate:8",
        "SFindBigDevBase",
    ),
    SelectorOperationRoute::new(
        0x001D,
        "selector-operation:_SlotManager:0x001D:d0-moveq-immediate:8",
        "SGetSRsrcPtr",
    ),
    SelectorOperationRoute::new(
        0x0020,
        "selector-operation:_SlotManager:0x0020:d0-moveq-immediate:8",
        "InitSDeclMgr",
    ),
    SelectorOperationRoute::new(
        0x0021,
        "selector-operation:_SlotManager:0x0021:d0-moveq-immediate:8",
        "SPrimaryInit",
    ),
    SelectorOperationRoute::new(
        0x0022,
        "selector-operation:_SlotManager:0x0022:d0-moveq-immediate:8",
        "SCardChanged",
    ),
    SelectorOperationRoute::new(
        0x0023,
        "selector-operation:_SlotManager:0x0023:d0-moveq-immediate:8",
        "SExec",
    ),
    SelectorOperationRoute::new(
        0x0024,
        "selector-operation:_SlotManager:0x0024:d0-moveq-immediate:8",
        "SOffsetData",
    ),
    SelectorOperationRoute::new(
        0x0025,
        "selector-operation:_SlotManager:0x0025:d0-moveq-immediate:8",
        "SInitPRAMRecs",
    ),
    SelectorOperationRoute::new(
        0x0026,
        "selector-operation:_SlotManager:0x0026:d0-moveq-immediate:8",
        "SReadPBSize",
    ),
    SelectorOperationRoute::new(
        0x0028,
        "selector-operation:_SlotManager:0x0028:d0-moveq-immediate:8",
        "SCalcStep",
    ),
    SelectorOperationRoute::new(
        0x0029,
        "selector-operation:_SlotManager:0x0029:d0-moveq-immediate:8",
        "SInitSRsrcTable",
    ),
    SelectorOperationRoute::new(
        0x002A,
        "selector-operation:_SlotManager:0x002A:d0-moveq-immediate:8",
        "SSearchSRT",
    ),
    SelectorOperationRoute::new(
        0x002B,
        "selector-operation:_SlotManager:0x002B:d0-moveq-immediate:8",
        "SUpdateSRT",
    ),
    SelectorOperationRoute::new(
        0x002C,
        "selector-operation:_SlotManager:0x002C:d0-moveq-immediate:8",
        "SCalcSPointer",
    ),
    SelectorOperationRoute::new(
        0x002D,
        "selector-operation:_SlotManager:0x002D:d0-moveq-immediate:8",
        "SGetDriver",
    ),
    SelectorOperationRoute::new(
        0x002E,
        "selector-operation:_SlotManager:0x002E:d0-moveq-immediate:8",
        "SPtrToSlot",
    ),
    SelectorOperationRoute::new(
        0x002F,
        "selector-operation:_SlotManager:0x002F:d0-moveq-immediate:8",
        "SFindSInfoRecPtr",
    ),
    SelectorOperationRoute::new(
        0x0030,
        "selector-operation:_SlotManager:0x0030:d0-moveq-immediate:8",
        "SFindSRsrcPtr",
    ),
    SelectorOperationRoute::new(
        0x0031,
        "selector-operation:_SlotManager:0x0031:d0-moveq-immediate:8",
        "SDeleteSRTRec",
    ),
]
